
name: Go Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and test
      run: |                         
        go build -v
        go mod init 
        go test -v deck_test.go    

    - name: Run Security Scan
      run: gosec ./...
