
name: Go CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build and test
      run: |                         
        go build -v
        go mod init 
        go test -v deck_test.go    

    - name: Run Security Scan
      run: gosec ./...
